### ISSUE TITLE
Show Notification, Not only console.log

### ISSUE THREAD

**Issue by b1tw0rker** [master-atul/web-push-demo#7]
Hi 

Maybe , you may help me.
I figured out evenrything fine.
But at least, how can i show the Notification message.
Your code:

self.addEventListener("push", function (event) {
    if (event.data) {
        console.log("Push event!! ", event.data.text());
    } else {
        console.log("Push event but no data");
    }
});

This will only produce a console.log
But how can i Show the Notification ?

Thanks for help, best regards

Nick

**Comment by a7ul** [comment]
Hi you need the local notification from second part of the blog
https://blog.atulr.com/web-notifications#step-2-local-notification

**Comment by b1tw0rker** [comment]
Sorry, that i tried also. It does not work well also.
I figured this out by my own, adding two lines your code:

self.addEventListener("push", function (event) {
    if (event.data) {
        console.log("Push event!! ", event.data.text());
       // added two new lines
        const promiseChain = self.registration.showNotification(event.data.text());
        event.waitUntil(promiseChain);
    } else {
        console.log("Push event but no data");
    }
});
